# Backend API Contract for Kubernetes Deployment
# This defines the expected API endpoints that the backend service will expose in the Kubernetes cluster

openapi: 3.0.0
info:
  title: Todo Chatbot Backend API
  version: 1.0.0
  description: API contract for the backend service in Kubernetes deployment

servers:
  - url: http://todo-backend:8000
    description: Backend service in Kubernetes cluster

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Verify the backend service is running
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  service:
                    type: string
                    example: "backend-api"

  /api/{user_id}/chat/:
    post:
      summary: AI Chat endpoint
      description: Send a message to the AI chatbot
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Chat response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string

  /api/{user_id}/tasks:
    get:
      summary: Get user tasks
      description: Retrieve all tasks for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of user tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    completed:
                      type: boolean

    post:
      summary: Create task
      description: Create a new task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean

  /api/{user_id}/tasks/{task_id}:
    put:
      summary: Update task
      description: Update an existing task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean

    delete:
      summary: Delete task
      description: Delete an existing task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema: integer
      responses:
        '204':
          description: Task deleted

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion
      description: Toggle the completion status of a task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema: integer
      responses:
        '200':
          description: Task completion toggled
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean